export class RandomCars {
  color: string;

  cars: string[] = [
    'Acura',
    'Daihatsu',
    'Datsun',
    'Honda',
    'Infiniti',
    'Isuzu',
    'Lexus',
    'Mazda',
    'Mitsubishi',
    'Nissan',
    'Scion',
    'Subaru',
    'Suzuki',
    'Toyota',
    'Buick',
    'Cadillac',
    'Chevrolet',
    'Chrysler',
    'Dodge',
    'Ford',
    'Hummer',
    'Jeep',
    'Lincoln',
    'Mercury',
    'Oldsmobile',
    'Pontiac',
    'Tesla',
    'Aurus',
    'Lada',
    'GAZ',
    'Moskvich',
    'UAZ',
    'Audi',
    'BMW',
    'Mercedes-Benz',
    'Opel',
    'Porsche',
    'Volkswagen',
    'Daewoo',
    'Genesis',
    'Hyundai',
    'Kia',
    'SsangYong',
    'Alfa Romeo',
    'Aston Martin',
    'Bentley',
    'Bugatti',
    'Citroen',
    'Ferrari',
    'Fiat',
    'Jaguar',
    'Lamborghini',
    'Lancia',
    'Land Rover',
    'Maserati',
    'Maybach',
    'Peugeot',
    'Renault',
    'Rolls-Royce',
    'Rover',
    'Skoda',
    'Smart',
    'Volvo',
    'Brilliance',
    'Changan',
    'Chery',
    'CheryExeed',
    'DongFeng',
    'Geely',
    'Great Wall',
    'Haima',
    'Haval',
    'Lifan',
    'Luxgen',
    'Zotye',
  ];

  models: string[] = [
    'i3',
    'X1',
    'X2',
    'X3',
    'X4',
    'X5',
    'X6',
    '80',
    '90',
    '100',
    '200',
    'A1',
    'A2',
    'A3',
    'A4',
    'A5',
    'A6',
    'Accord',
    'Avancier',
    'Civic',
    'Civic Ferio',
    'CR-V',
    'Element',
    'Pilot',
    'Logo',
    'Crosstour',
    'Odyssey',
    'Defender',
    'Discovery',
    'Range Rover',
    'Evoque',
    'Freelander',
    'Almera',
    'Avenir',
    'Cube',
    'Juke',
    'Micra',
    'Leaf',
    'Tiida',
    'Sunny',
    'X-Trail',
    'Serena',
    'Aveo',
    'Blazer',
    'Camaro',
    'Cruze',
    'Cobalt',
    'Lacetti',
    'Epica',
    'Express',
    'Viva',
    'Niva',
    'Lumina',
    'Berlingo',
    'Jumpy',
    'Xantia',
    'Xsara',
    'Jumper',
    'Damas',
    'Espero',
    'Gentra',
    'Lanos',
    'Matiz',
    'Magnus',
    'Nexia',
    'C-MAX',
    'Contour',
    'EcoSport',
    'Ecoline',
    'Escape',
    'Explorer',
    'Galaxy',
    'Kuga',
    'Ranger',
    'Focus',
    'Fusion',
    'Fiesta',
    'ASX',
    'Carisma',
    'Colt',
    'Eclipce Cross',
    'Mirage',
    'Pajero',
    'Sigma',
    'Fabia',
    'Favorit',
    'Felecia',
    'Karoq',
    'Octavia',
    'Rapid',
    'Yeti',
    'Roomster',
    'Forester',
    'Impreza',
    'Legacy',
    'Tribeca',
    'Outback',
    'XV',
  ];

  createRandomColor(): string {
    const letters = '0123456789abcdef';
    this.color = '#';
    for (let i = 0; i < 6; i++) {
      this.color += letters[Math.floor(Math.random() * 16)];
    }
    return this.color;
  }

  createRandomName(): string {
    const carBrand = this.cars[Math.floor(Math.random() * this.cars.length)];
    const carModel = this.models[Math.floor(Math.random() * this.models.length)];
    return `${carBrand} ${carModel}`;
  }
}
